[package]
name = "segtree"
version = "0.1.0"
edition = "2021"

[lib]
name = "segtree_native"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module", "abi3-py311"] }
thiserror = "2.0.16"
