[project]
name = "pysegtree"
version = "0.1.0"

[build-system]
requires = ["maturin>=1.5"]
build-backend = "maturin"

[tool.maturin]
packages = ["pysegtree"]        
module-name = "pysegtree.segtree_native" 
