name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11", "3.12"]
    runs-on: ${{ matrix.os }} 
    steps:
      - uses: actions/checkout@v4

      # Rust (stable)
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cargo tests
        run: cargo test --verbose

      # Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python test deps
        run: |
          python -m pip install -U pip
          python -m pip install pytest maturin

      - name: Build extension (dev) & run pytest
        run: |
          maturin develop --release
          pytest -q
