name: wheels
on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --strip -o dist
          manylinux: "2014"
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-linux
          path: dist/*

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --strip -o dist
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-windows
          path: dist/*

